Repository caicloud/build-infra, pull requests merged in 2018-04, with the labels that each got.

#7 fix(prebuild): avoid duplicate generation of caimake.sh
  Makefile.expansion
  hack/caimake/caimake.sh
  hack/make-rules/unfold.sh
  pkg/caimake/cmd/bindata.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/S

#8 fix: avoid modification timestamp changed in bindata.go
  Makefile.expansion
  pkg/caimake/cmd/bindata.go
Labels: caicloud-cla: yes, release-note, size/S

#10 fix(update): avoid updating when current version is equal to latest
  pkg/caimake/cmd/update.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XS

#11 chore(*): remove unuseful space
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#12 fix: use $$ replace $ in pre build
  Makefile.expansion
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
